// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqjkedmjefefohhxgffd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxamtlZG1qZWZlZm9oaHhnZmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODkxODAsImV4cCI6MjA2MzE2NTE4MH0.1evYDr4jb8D-QRo06mdDjVzX2RYt5mtUS4yfhaGu2CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);